# Copyright (C) 2025 - 2026 Advanced Micro Devices, Inc.
# SPDX-License-Identifier: Apache-2.0

[clock]
freqHz=100000000:mm2s
freqHz=100000000:s2mm
freqHz=100000000:square
[connectivity]
nk=s2mm:1:s2mm
nk=mm2s:1:mm2s
nk=square:1:square
